# Example usage of paw_ansible_role_php

# Simple include with default parameters
include paw_ansible_role_php

# Or with custom parameters:
# class { 'paw_ansible_role_php':
#   php_apc_shm_size => '96M',
#   php_apc_enable_cli => '0',
#   php_fpm_daemon => undef,
#   php_fpm_conf_path => undef,
#   php_opcache_zend_extension => 'opcache.so',
#   php_opcache_enable => '1',
#   php_opcache_enable_cli => '0',
#   php_opcache_memory_consumption => '96',
#   php_opcache_interned_strings_buffer => '16',
#   php_opcache_max_accelerated_files => '4096',
#   php_opcache_max_wasted_percentage => '5',
#   php_opcache_validate_timestamps => '1',
#   php_opcache_revalidate_path => '0',
#   php_opcache_revalidate_freq => '2',
#   php_opcache_max_file_size => '0',
#   php_opcache_blacklist_filename => undef,
#   php_short_open_tag => 'Off',
#   php_precision => 14,
#   php_output_buffering => '4096',
#   php_serialize_precision => '-1',
#   php_expose_php => 'On',
#   php_max_execution_time => '60',
#   php_max_input_time => '60',
#   php_max_input_vars => '1000',
#   php_memory_limit => '256M',
#   php_error_reporting => 'E_ALL & ~E_DEPRECATED & ~E_STRICT',
#   php_display_errors => 'Off',
#   php_display_startup_errors => 'Off',
#   php_post_max_size => '32M',
#   php_realpath_cache_size => '32K',
#   php_file_uploads => 'On',
#   php_upload_max_filesize => '64M',
#   php_max_file_uploads => '20',
#   php_allow_url_fopen => 'On',
#   php_date_timezone => 'America/Chicago',
#   php_sendmail_path => '/usr/sbin/sendmail -t -i',
#   php_session_save_handler => 'files',
#   php_session_save_path => undef,
#   php_session_cookie_lifetime => 0,
#   php_session_gc_probability => 1,
#   php_session_gc_divisor => 1000,
#   php_session_gc_maxlifetime => 1440,
#   php_fpm_pool_user => undef,
#   php_fpm_pool_group => undef,
#   php_enablerepo => undef,
#   php_packages_extra => [],
#   php_packages_state => 'present',
#   php_install_recommends => true,
#   php_enable_webserver => true,
#   php_enable_php_fpm => false,
#   php_fpm_state => 'started',
#   php_fpm_handler_state => 'restarted',
#   php_fpm_enabled_on_boot => true,
#   php_fpm_listen => '127.0.0.1:9000',
#   php_fpm_listen_allowed_clients => '127.0.0.1',
#   php_fpm_pm_max_children => 50,
#   php_fpm_pm_start_servers => 5,
#   php_fpm_pm_min_spare_servers => 5,
#   php_fpm_pm_max_spare_servers => 5,
#   php_fpm_pm_max_requests => 0,
#   php_fpm_pm_status_path => undef,
#   php_fpm_pools => [{'pool_name' => 'www', 'pool_template' => 'www.conf.j2', 'pool_listen' => '{{ php_fpm_listen }}', 'pool_listen_allowed_clients' => '{{ php_fpm_listen_allowed_clients }}', 'pool_pm' => 'dynamic', 'pool_pm_max_children' => '{{ php_fpm_pm_max_children }}', 'pool_pm_start_servers' => '{{ php_fpm_pm_start_servers }}', 'pool_pm_min_spare_servers' => '{{ php_fpm_pm_min_spare_servers }}', 'pool_pm_max_spare_servers' => '{{ php_fpm_pm_max_spare_servers }}', 'pool_pm_max_requests' => '{{ php_fpm_pm_max_requests }}', 'pool_pm_status_path' => '{{ php_fpm_pm_status_path }}'}],
#   php_executable => 'php',
#   php_enable_apc => true,
#   php_use_managed_ini => true,
#   php_disable_functions => [],
#   php_install_from_source => false,
#   php_source_repo => 'https://github.com/php/php-src.git',
#   php_source_version => 'master',
#   php_source_clone_dir => '~/php-src',
#   php_source_clone_depth => 1,
#   php_source_install_path => '/opt/php',
#   php_source_install_gmp_path => '/usr/include/x86_64-linux-gnu/gmp.h',
#   php_source_mysql_config => '/usr/bin/mysql_config',
#   php_source_make_command => 'make',
#   php_source_configure_command => './configure --prefix={{ php_source_install_path }} --with-config-file-path={{ php_conf_paths | first }} --enable-mbstring --enable-zip --enable-bcmath --enable-pcntl --enable-ftp --enable-exif --enable-calendar --enable-opcache --enable-pdo --enable-sysvmsg --enable-sysvsem --enable-sysvshm --enable-wddx --with-curl --with-mcrypt --with-iconv --with-gmp --with-pspell --with-gd --with-jpeg-dir=/usr --with-png-dir=/usr --with-zlib-dir=/usr --with-xpm-dir=/usr --with-freetype-dir=/usr --enable-gd-native-ttf --enable-gd-jis-conv --with-openssl --with-pdo-mysql=/usr --with-gettext=/usr --with-zlib=/usr --with-bz2=/usr --with-recode=/usr --with-mysqli={{ php_source_mysql_config }}\n',
# }
